### ISSUE TITLE
None of the following functions can be called with the arguments supplied

### ISSUE THREAD

**Issue by keesunguyen** [michael-cheung-thebus/boot_completed#2]
package com.example.sooh

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;

class BootReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != null) {
            if (intent.action !! == Intent.ACTION_BOOT_COMPLETED || intent.action !! == Intent.ACTION_LOCKED_BOOT_COMPLETED) {
                val i = Intent(context, MainActivity::class.java);
                context.startActivity(i);
            }
        }
    }
}

But when after device reboot then catch "Unfortunately, sooh has stopped"

**Comment by michael-cheung-thebus** [comment]
The code you've posted is just a plain Android boot receiver - nothing to do with this plugin for Flutter.  Try asking on [stackoverflow](https://stackoverflow.com/questions) if you have a specific question about how to create a boot receiver.

If you're having trouble using this plugin, take a look at the [readme](https://pub.dev/packages/boot_completed) and the [example code](https://github.com/michael-cheung-thebus/boot_completed/tree/master/example/android/app/src/main/kotlin/org/thebus/boot_completed_example), and open a new issue with details on exactly what you're having trouble with.
